### ISSUE TITLE
Add venue map

### ISSUE THREAD

**Issue by miketheman** [psf/pycon-us-mobile#16]
Useful image to help navigate the space.

Once exists, maybe display in a Talk with the location highlighted

**Comment by lhmzhou** [comment]
Asset can be found [here](https://assets.simpleviewinc.com/simpleview/image/upload/v1/clients/saltlake/SaltPalaceFloorPlans2012_a4dfe676-a3c9-468f-8bde-ae51c56480c8.pdf). Gonna be hard to view on a mobile screen, but would be a nice add-on!
