### ISSUE TITLE
Persistence for User Preferences  and Favorited sessions

### ISSUE THREAD

**Issue by ewdurbin** [psf/pycon-us-mobile#25]
Currently preferences like dark mode, and the list of sessions marked as "favorite" are not persisted.

These should be persisted to the device, and also sync'd to us.pycon.org.

We'll need to design an an API endpoint, but I expect it to look something like:

```
GET/PATCH/POST /v1/api/user/mobile-state

{
    "favorited_sessions": [{list of session ids}],
    "preferences": {
        "dark_mode": true,
        "start_page": "/app/pages/schedule"
    }
}
```

**Comment by brandtbucher** [comment]
+1, came here to open an issue for this. Just finished going through all of the sessions and "favoriting" the ones I wanted to see. After being prompted to "live update" the app, I was still logged in but all of the favorites were gone. Pretty frustrating. :(

**Comment by ewdurbin** [comment]
live update containing fix should be live. its not quite perfect yet, but is at least persisting locally and to the backend as able.

reopening since it will need a lil improvement.
