### ISSUE TITLE
The "About" page is empty

### ISSUE THREAD

**Issue by brandtbucher** [psf/pycon-us-mobile#27]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The "About" page is empty.

**Expected behavior:**

The "About" page is not empty.

**Steps to reproduce:**

On iOS, tap on the menu icon at the top left, and then tap on "About".

**Comment by ewdurbin** [comment]
Yep! we'll be populating this as we approach the conference.
