### ISSUE TITLE
The "All", "Favorites", and "Filter" buttons don't do anything on the "Speakers" page

### ISSUE THREAD

**Issue by brandtbucher** [psf/pycon-us-mobile#28]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Tapping on any of these buttons seems to have no effect on the content displayed.

**Expected behavior:**

Since it's not possible to "favorite" or filter speakers (like you can with talks), I would not expect these buttons to exist.

**Steps to reproduce:**

On iOS, tap on "Speakers" at the bottom right, and tap on any of the mentioned buttons at the top of the screen.

**Comment by ewdurbin** [comment]
removed in #30, we could update this issue to ask if anyone wants to implement favorites for speakers.

**Comment by brandtbucher** [comment]
Thanks for the quick responses!

**Comment by ewdurbin** [comment]
live update containing fix should be live. its not quite perfect yet, but is at least persisting locally and to the backend as able.

**Comment by ewdurbin** [comment]
No intention to add favorite/filter for speakers tab.
