### ISSUE TITLE
Broken sponsor image

### ISSUE THREAD

**Issue by miketheman** [psf/pycon-us-mobile#34]
All logos load but one.

![Screenshot_20230407-064043.png](https://user-images.githubusercontent.com/529516/230536408-38217383-4c52-4ec3-8dd3-a718a515e355.png)

**Comment by ewdurbin** [comment]
Appears this is consistent across mobile and web, so not an issue with pycon-us-mobile per se. Rather the sponsor provided a .eps file at signup.

I've generated a matching png and it should flow through python.org, us.pycon.org, and the mobile app over time.
