### ISSUE TITLE
Android: dark mode and sessions filter don't persist

### ISSUE THREAD

**Issue by hugovk** [psf/pycon-us-mobile#35]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Steps to reproduce:**

On Android/Samsung S22:

1. Press the filters icon at the top right
2. Untick Charla and press Done
3. Press the menu icon at the top left
4. Select Dark Mode
5. Confirm app shows in dark mode and charlas are hidden
6. Quit the app, for example by pressing the Android menu button and swiping the app up
7. Open the app again

**Current behavior:**

Resets to light mode with charlas shown

**Expected behavior:**

Remains in dark mode with charlas hidden

**Comment by miketheman** [comment]
@hugovk I put up a couple of PRs to implement the desired behaviors. Please check them out and see if they do what you'd expect, and if there are any bugs you can find.

**Comment by hugovk** [comment]
Thanks! How can I test them out?

**Comment by miketheman** [comment]
I guess check out the code, compile and run in an emulator?

**Comment by hugovk** [comment]
I'm not sure how to run in an emulator:

I've followed the steps at https://github.com/psf/pycon-us-mobile#getting-started and have it running in a normal Chrome window on macOS. I can change the settings and close the tab, but they're reset when re-opening.

**Comment by ewdurbin** [comment]
https://github.com/psf/pycon-us-mobile/pull/44 wraps this up.

**Comment by hugovk** [comment]
Tested latest update on Android and confirmed fixed, thank you!
