### ISSUE TITLE
Open on current day during the conference

### ISSUE THREAD

**Issue by hugovk** [psf/pycon-us-mobile#39]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Here's a test branch that uses a local `conferences.json` and modifies the date to 7-11 April:

https://github.com/hugovk/pycon-us-mobile/tree/modify-dates-for-testing

1. Open the app on Sunday 9th April
2. The schedule for the first day is shown, Friday 7th April
3. Have to press the SUN tab to see today 

**Expected behavior:**

During the conference, it would be nice if the app opened on the current day.

**Comment by ewdurbin** [comment]
Went for bonus in https://github.com/psf/pycon-us-mobile/commit/751b2c121cdd85645ba5c42865891e8b9079b8e2 to scroll to the current time too. classes are there and logic is sound, but I can't actually get the scroll to happen.

**Comment by hugovk** [comment]
After updating this morning, it's opening on the first day (Wednesday) instead of today (Saturday).

I can reproduce on Android, but not on local when testing on Chrome/macOS.

**Comment by hugovk** [comment]
And with the latest update it's working again! 👏
