### ISSUE TITLE
Add Lunch Description

### ISSUE THREAD

**Issue by lhmzhou** [psf/pycon-us-mobile#48]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When you navigate to a breakfast/lunch card, it's missing meal options for that particular day. 

**Expected behavior:**
Would be nice to see what we're having during meal time. 

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by ewdurbin** [comment]
This is planned! Look for an update in the app in the coming days.

**Comment by ewdurbin** [comment]
This is done.
