### ISSUE TITLE
Connect to ShareMy.Health and surface our status

### ISSUE THREAD

**Issue by lhmzhou** [psf/pycon-us-mobile#49]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Required to download the [ShareMy.Health](https://www.sharemy.health/) app. 

**Expected behavior:**
Would like to see the [ShareMy.Health](https://www.sharemy.health/) status on the PyCon app. 1 less app to deal with. 

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by ewdurbin** [comment]
Hi @lhmzhou this is a great suggestion, but ShareMy.Health will only accept their app/passport for check-in.
