### ISSUE TITLE
Time field too long

### ISSUE THREAD

**Issue by hugovk** [psf/pycon-us-mobile#57]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The date string above talks is rather long: day, full date, time with seconds, timezone and offset etc. 

![Screenshot_20230421_093605_PyCon US 2023](https://user-images.githubusercontent.com/1324225/233678250-49b65083-3c54-4774-b94e-c083dc5bea6d.jpg)

**Expected behavior:**

day and hh:mm should be enough? 

**Steps to reproduce:**

Open schedule on Android

**Comment by hugovk** [comment]
It's in `src/app/pages/schedule/schedule.html` from https://github.com/psf/pycon-us-mobile/commit/751b2c121cdd85645ba5c42865891e8b9079b8e2:

```ts
        <ion-label [class]="(group.startTime < currentTime)? 'past': (group.startTime)? 'future' : 'non'">
          {{days[dayIndex].day}} - {{group.time}} {{group.startTime}} {{currentTime}}
        </ion-label>
```

**Comment by ewdurbin** [comment]
https://github.com/psf/pycon-us-mobile/commit/ea706d6f7b9df936bd53eab190d8243cb47ba732 resolves.
