### ISSUE TITLE
Dark Mode - some sponsor list logos not visible

### ISSUE THREAD

**Issue by oliviasauls** [psf/pycon-us-mobile#65]
In dark mode, some of the sponsor logos in the sponsor list aren't visible (black font on black background) 

ie: Temporal, Anvil, Ansys is hard to see, Python Engineering

![img_6041_720_720](https://github.com/psf/pycon-us-mobile/assets/89146495/f1b63ada-fe43-4b12-a444-c96bed808a3b)
![img_6042_720_720](https://github.com/psf/pycon-us-mobile/assets/89146495/bea6cf63-84dd-43c9-8bd8-36fc16fc7c3b)
![img_6040_720_720](https://github.com/psf/pycon-us-mobile/assets/89146495/0648ca9b-38d3-4e71-a341-280d418ed2a5)

**Comment by ewdurbin** [comment]
Probably best to force a white background behind all logos (including footer). but i think that would be rather jarring in "dark mode".

**Comment by keshav861** [comment]
Probably best way is when we switch from light to dark mode we can shift colors from black to white or some other color ad for images we can switch images too with the others which are visible with the dark mode.

**Comment by ewdurbin** [comment]
@keshav861 I think that would be ideal, but we are unlikely to get dark-mode compatible logos from all sponsors. 9acefa234858122abf3c04e4a547992df23cd0c2 addresses this for now.
