### ISSUE TITLE
Looping Sponsor Footer Logos - Wrong Size/Contrast in Dark Mode

### ISSUE THREAD

**Issue by oliviasauls** [psf/pycon-us-mobile#69]
**I'm submitting a ...**  (check one with "x")
[] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Many of the sponsor logos are either too small or blend into the footer in dark mode.

**Expected behavior:**
Logos rendering bigger or having a contrasted background so that they're visible in dark mode.

 
**Examples**

![img_6355_720](https://github.com/psf/pycon-us-mobile/assets/89146495/680c601f-200e-49c1-91cc-37a2df55712e)
![img_6356_720](https://github.com/psf/pycon-us-mobile/assets/89146495/ef9ced14-fc80-425c-8e25-8b17a9fcf459)
![img_6354_720](https://github.com/psf/pycon-us-mobile/assets/89146495/be802fd8-0e0c-4ae7-aea8-93fcb08f25d0)

**Comment by ewdurbin** [comment]
added a white background in e5007f9abbc87ad7fa830040ba3e754061d70199, it will go out in the next release, next week.

the sizing is due to aspect-ratio of the space and will not change. if sponsors want "more" they need to submit wider aspect-ratio logs.
